=== Tanmoy4672/XML_Code/Mapping XML/employees.xsd
<schema targetNamespace="http://www.empinfo.com"
xmlns="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">
<element name="employees">
<complexType>
<sequence>
<element name="employee" minOccurs="0" maxOccurs="unbounded">
<complexType>
<sequence>
<element name="empNo" type="int"/>
<element name="name" type="string"/>
<element name="salary" type="decimal"/>
</sequence>
</complexType>
 </element>
</sequence>
</complexType>
</element>
</schema>

=== Tanmoy4672/XML_Code/Mapping XML/employees.xml
<employees 
xmlns="http://www.empinfo.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation=
"http://www.empinfo.com D://Worked File/XML work File/Mapping XML/employees.xsd">
<employee>
<empNo>101</empNo>
<name>Tanmoy</name>
<salary>12000</salary>
</employee>
<employee>
<empNo>102</empNo>
<name>Tamol</name>
<salary>10000</salary>
</employee>
</employees>
